### ISSUE TITLE
Error in Webpack 5

### ISSUE THREAD

**Issue by ccorcos** [browserify/path-browserify#23]
Looks like require.resolve doesnt work anymore in Webpack 5?

```
ERROR in ./src/renderer/services/Config.ts 26:26-41
Module not found: Error: Can't resolve 'path' in '/Users/chet/Code/brain-web/object-system/src/renderer/services'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "path": require.resolve("path-browserify") }'
	- install 'path-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "path": false }
 @ ./src/renderer/renderer.tsx 26:17-45
```

**Comment by goto-bus-stop** [comment]
Have you added the options suggested by the error message to your webpack config?

**Comment by ccorcos** [comment]
Yeah, i definitely have `npm install --save path-browserify` in there. Let me come back to you with a repro.

**Comment by goto-bus-stop** [comment]
That's one half of it, the `resolve.fallback` option in the webpack config must also be set correctly.

**Comment by ccorcos** [comment]
Oh snap, I thought that was an either/or kind of thing. Sorry about this!

**Comment by nhhockeyplayer** [comment]
this is outrageous and needs to be added to all spa on the planet bow

**Comment by xptodevx** [comment]
sorry but I'm having the same issue.
the project was working flawlessly, running and I was developing. all of sudden it starts breaks everyting, I didnt' any npm install whatsoever, it just break up and refuses to compile now.
I'm totally hopeless and very upset because its a very complex project I lost several days working, including nights now, it refuses to compile and I'm sure, I DIDN'T CHANGED ANYTHING, it breaks alone by itself. Even if I did I never messed the config js, never ever touched. It breaks.

Read this messy here please.
Its completelhy unforgiven working on something that can break by itself and its not reliable, its very hard to anyone who wants to build something see their work be destroyed without any explanation like that.


2 warnings have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

ERROR in ./node_modules/destroy/index.js 12:17-41
Module not found: Error: Can't resolve 'fs' in '/MYCOMPUTER/wallet-integration-template/node_modules/destroy'
 @ ./node_modules/send/index.js 19:14-32
 @ ./node_modules/express/lib/response.js 47:11-26
 @ ./node_modules/express/lib/express.js 27:10-31
 @ ./node_modules/express/index.js 10:0-41
 @ ./src/js/mint/app.mjs 3:0-31
 @ ./src/main.js 185:19-46

ERROR in ./node_modules/etag/index.js 22:12-31
Module not found: Error: Can't resolve 'fs' in '/MYCOMPUTER/wallet-integration-template/node_modules/etag'
 @ ./node_modules/express/lib/utils.js 25:11-26
 @ ./node_modules/express/lib/application.js 30:18-48 32:25-62 34:19-50
 @ ./node_modules/express/lib/express.js 19:12-36
 @ ./node_modules/express/index.js 10:0-41
 @ ./src/js/mint/app.mjs 3:0-31
 @ ./src/main.js 185:19-46

ERROR in ./node_modules/express/lib/request.js 18:11-30
Module not found: Error: Can't resolve 'net' in '/MYCOMPUTER/wallet-integration-template/node_modules/express/lib'
 @ ./node_modules/express/lib/express.js 25:10-30
 @ ./node_modules/express/index.js 10:0-41
 @ ./src/js/mint/app.mjs 3:0-31
 @ ./src/main.js 185:19-46

ERROR in ./node_modules/express/lib/view.js 18:9-22
Module not found: Error: Can't resolve 'fs' in '/MYCOMPUTER/wallet-integration-template/node_modules/express/lib'
 @ ./node_modules/express/lib/application.js 26:11-28
 @ ./node_modules/express/lib/express.js 19:12-36
 @ ./node_modules/express/index.js 10:0-41
 @ ./src/js/mint/app.mjs 3:0-31
 @ ./src/main.js 185:19-46

ERROR in ./node_modules/mime/mime.js 3:9-22
Module not found: Error: Can't resolve 'fs' in '/MYCOMPUTER/wallet-integration-template/node_modules/mime'
 @ ./node_modules/send/index.js 31:11-26
 @ ./node_modules/express/lib/response.js 47:11-26
 @ ./node_modules/express/lib/express.js 27:10-31
 @ ./node_modules/express/index.js 10:0-41
 @ ./src/js/mint/app.mjs 3:0-31
 @ ./src/main.js 185:19-46

ERROR in ./node_modules/send/index.js 29:9-22
Module not found: Error: Can't resolve 'fs' in '/MYCOMPUTER/wallet-integration-template/node_modules/send'
 @ ./node_modules/express/lib/response.js 47:11-26
 @ ./node_modules/express/lib/express.js 27:10-31
 @ ./node_modules/express/index.js 10:0-41
 @ ./src/js/mint/app.mjs 3:0-31
 @ ./src/main.js 185:19-46

6 errors have detailed information that is not shown.
Use 'stats.errorDetails: true' resp. '--stats-error-details' to show it.

webpack 5.48.0 compiled with 6 errors and 2 warnings in 13344 ms
ℹ ｢wdm｣: Failed to compile.



I'm sure this project waas up running 100% for god sake! There's no stackoverflow now capable of helping me. This is beyond of frustrating this is hard as fuck.... why???? why????

**Comment by goto-bus-stop** [comment]
I don't see anything about the `path` module in there, so it is not relevant to this issue. are you webpacking server code?

**Comment by maxiujin** [comment]
I was running npm run build all night didn't change my code and suddenly when I ran npm build I get this webpack error out of no where.

**Comment by rabira-hierpa** [comment]
@maxiujin maybe you can try to  polyfill node core modules in webpack 5  by using [this guide](https://www.alchemy.com/blog/how-to-polyfill-node-core-modules-in-webpack-5)
